<?php

namespace App\Controllers\Dna;

use App\Controllers\BaseController;
use App\Models\CardModel;
use App\Models\MenuModel;
use App\Models\ProductModel;
use CodeIgniter\HTTP\RedirectResponse;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;

class Products extends BaseController
{

    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub

        MenuModel::setActive(__CLASS__);
    }

    public function index() : string
    {
        $db = db_connect();
        $model = new ProductModel();
        $products = $model->getAll(100);

        return view('dna/products', [
            'products' => $products,
        ]);

    }


}